### ISSUE TITLE
V1 - Secure Development - Verify use of threat modeling for applications in IoT ecosystem

### ISSUE THREAD

**Issue by dansecops** [OWASP/IoT-Security-Verification-Standard-ISVS#30]
The ASVS suggests the use of threat modelling for every design change - 1.1.2 (Secure Software Development Lifecycle Requirements) and the protection against identified risks or threats - 11.1.5 (Business Logic Security Requirements).

It would be helpful to add a similar requirement to suggest threat modelling or similar methodologies for identification of all application threats and risks specifically in the IoT ecosystem. This would fall under section `V1: IoT Ecosystem Requirements`.

Suggestion: 
* **Option 1**: Modify existing requirements in `1.1 - Application and Ecosystem Design` or `1.3 Secure Development` to include the use of threat modeling or similar methodologies for protecting applications in the IoT ecosystem based on likely security risks or threats.

* **Option 2**: Add new requirement to section `1.1 - Application and Ecosystem Design`:

**`1.1.7 Verify the use of threat modeling or similar methodologies for each application in in the IoT ecosystem based on likely security risks or threats | ✓ | ✓ | ✓ |`**

Please share your thoughts on this.

**Comment by scriptingxss** [comment]
Agreed. Modifying 1.1.3 might be the best way forward. Perhaps with the following?

`Verify the use of threat modeling for every product introduction design (i.e. new and mature), security-critical feature change, or sprint planning to identify threats, plan for countermeasures, facilitate appropriate risk responses, and guide security testing.`

**Comment by dansecops** [comment]
Yes, that sounds good to keep the control in 1.1.3  would suggest to keep it a bit shorter:

```Verify the use of threat modelling for each design or security-relevant product feature change to identify likely threats and facilitate appropriate risk responses and to guide security testing.```

**Comment by scriptingxss** [comment]
I think it's important to use "product introduction' since it's one of the earliest stages in a product's lifecycles ( i.e. new product introduction (NPI)) where security teams may have feedback and provide influence. It does make it a bit longer but captures key use cases to threat model and how that feeds into testing. 

Revised requirement:
`Verify the use of threat modeling as part of each product introduction design (i.e. new and mature) and security-relevant feature changes to identify likely threats and facilitate appropriate risk responses to guide security testing.`

**Comment by dansecops** [comment]
Yes, that's makes sense to add this then. I've included this in the PR and updated the revised version (including using the correct AE spelling of threat modeling :))

**Comment by scriptingxss** [comment]
Merged! Thank you 🙏
