### ISSUE TITLE
3.1.1 limited to network locations over TCP/IP

### ISSUE THREAD

**Issue by scradster** [OWASP/IoT-Security-Verification-Standard-ISVS#45]
https://github.com/OWASP/IoT-Security-Verification-Standard-ISVS/blame/4582968e2b0323a02cfba36b9d32584d4eb0489a/en/V3-Software_Platform_Requirements.md#L17

This should apply to any network location, not only TCP/IP based ones (e.g. NFS and TFTP use UDP and are typical protocols used for network boot).

Suggestion:

`Verify that the bootloader does not allow code to be loaded from arbitrary locations. Locations include both local storage (SD, USB, etc.) and network locations (NFS, TFTP, etc.).`

**Comment by scriptingxss** [comment]
Thanks! Since secure boot starts at Level 2, I think we may want to adjust this control's leveling to match. (Thoughts? @cbassem)  

We can refine this requirement to use the following:

`Verify that the bootloader does not allow code loaded from arbitrary locations including both local storage (e.g. SD, USB, etc.) and network locations (e.g. NFS, TFTP, etc.).`

**Comment by cbassem** [comment]
@scriptingxss I've thought some more about this one and I agree with the proposed phrasing and level.
