### ISSUE TITLE
1.2.9 should be moved below 5.1.7

### ISSUE THREAD

**Issue by scradster** [OWASP/IoT-Security-Verification-Standard-ISVS#52]
https://github.com/OWASP/IoT-Security-Verification-Standard-ISVS/blame/4582968e2b0323a02cfba36b9d32584d4eb0489a/en/V1-IoT_Ecosystem_Requirements.md#L39

https://github.com/OWASP/IoT-Security-Verification-Standard-ISVS/blame/4582968e2b0323a02cfba36b9d32584d4eb0489a/en/V5-Hardware_Platform_Requirements.md#L23

1.2.9 is going one step further than 5.1.7 but both aim to the same goal, so they should be put in the same table.

I also doubt the benefit of 5.1.7 since it makes no real difference for an attacker if the header is populated or not. If the pads are there, accessing the (JTAG) interface is easy anyway.

**Comment by scriptingxss** [comment]
Agree, we will should move 1.2.9 to the hardware section. 

5.1.7 is an added layer requiring skills and tools attackers need in order to start poking around. It's not a security control per se but its raises the barrier of entry to identify vulnerabilities in hardware. If soldered headers are already on the board, it saves the attacker reverse engineering time to enumerate test points and pads. 

JTAG without secure JTAG may be easy if there are openocd configs for the target board (i.e. TAP or DAP offsets, reset pin offsets, etc.)or purchasing expensive commercial JTAG debuggers that have configs preloaded. UART could be super simple if not protected but does not give full access to memory or the processor like JTAG does. 

With that said, perhaps the control objective should be modified to reflect some of these considerations.?

**Comment by scriptingxss** [comment]
Updates applied 
https://github.com/OWASP/IoT-Security-Verification-Standard-ISVS/commit/d7b1fcdf41e3440f32223c5eaa6ce94e3ce95ac8
https://github.com/OWASP/IoT-Security-Verification-Standard-ISVS/commit/75b251dc95a446546fbe988b1e6e6d238f77c197
