### ISSUE TITLE
5.1.8 is unclear and hard to verify

### ISSUE THREAD

**Issue by scradster** [OWASP/IoT-Security-Verification-Standard-ISVS#53]
https://github.com/OWASP/IoT-Security-Verification-Standard-ISVS/blame/4582968e2b0323a02cfba36b9d32584d4eb0489a/en/V5-Hardware_Platform_Requirements.md#L24

Maybe I don't understand the requirement correctly, but:

Since the requirement talks about hardware that is _chosen_ I understand that this is not hardware that was engineered inhouse. Given that I don't see how one would verify that no un(officially)documented features are in place rather than testing for this extensively. Is that the idea of the requirement?

**Comment by scriptingxss** [comment]
It sounds like it would be better to remove the specificity of _chosen_. Hardware is always sourced whether it's in-house or otherwise. The design of hardware varies on the supplier model - ODM, JDM, etc. 

Regrading verification, one would need to review schematics, data sheets, and reverse engineer components to investigate whether such hardware debug features exist. The level of effort varies but these can be caught in design stages if security teams have access to platform documents and preproduction boards (i.e. EVT, DVT, PVT) or by third-parties after mass production (not preferred but is often the case without having the required in-house skillsets). 

Revised requirement below

`Verify that hardware has no unofficially documented debug features, such as special pin configurations that can enable or disable certain functionality.`

**Comment by scriptingxss** [comment]
https://github.com/OWASP/IoT-Security-Verification-Standard-ISVS/commit/75b251dc95a446546fbe988b1e6e6d238f77c197
