### ISSUE TITLE
2.3.5. Privacy Policy

### ISSUE THREAD

**Issue by cetome** [OWASP/IoT-Security-Verification-Standard-ISVS#73]
This is a strong requirement for GDPR and probably other legislations: "verify that the product has a data protection / privacy policy".

**Comment by scriptingxss** [comment]
Privacy is an interesting topic that we chose to address with logging and data protection sections. We deliberately opted to exclude policy and process oriented requirements outside of a disclosure policy and threat modeling which security teams may be responsible for (and they're extremely important to IoT security programs). Typically legal teams (or privacy orgs in big companies) would be responsible for defining a data protection / policy rather than security teams. Although important, privacy does not directly correlate to the security of connected products.
